export const FIREBASE_SUB_ERROR = 'FIREBASE_SUB_ERROR'
export const FIREBASE_SUB_SUCCESS = 'FIREBASE_SUB_SUCCESS'
export const FIREBASE_SUB_FIRED = 'FIREBASE_SUB_FIRED'
export const FIREBASE_SUB_RESET = 'FIREBASE_SUB_RESET'
export const FIREBASE_SUB_INVALID = 'FIREBASE_SUB_INVALID'

export const FIREBASE_LOG_FIRED = 'FIREBASE_LOG_FIRED'
export const FIREBASE_LOG_SUCCESS = 'FIREBASE_LOG_SUCCESS'
export const FIREBASE_LOG_ERROR = 'FIREBASE_LOG_ERROR'

// - MISSION
export const MISSION_NEW_ERROR = 'MISSION_NEW_ERROR';
export const MISSION_NEW_SUCCESS = 'MISSION_NEW_SUCCESS';
export const MISSION_NEW_FIRED = 'MISSION_NEW_FIRED';
export const MISSION_NEW_VE = 'MISSION_NEW_VE';
export const MISSION_SET = 'MISSION_SET';
export const MISSION_FLIST = 'MISSION_FLIST';
// - PARTICIPANTs
export const NEW_PARTICIPANT_FIRED = 'NEW_PARTICIPANT_FIRED';
export const NEW_PARTICIPANT_ERROR = 'NEW_PARTICIPANT_ERROR';
export const NEW_PARTICIPANT_VE = 'NEW_PARTICIPANT_VE';
export const NEW_PARTICIPANT_SUCCESS = 'NEW_PARTICIPANT_SUCCESS';