export const FIREBASE_SUB_ERROR = 'FIREBASE_SUB_ERROR'
export const FIREBASE_SUB_SUCCESS = 'FIREBASE_SUB_SUCCESS'
export const FIREBASE_SUB_FIRED = 'FIREBASE_SUB_FIRED'
export const FIREBASE_SUB_RESET = 'FIREBASE_SUB_RESET'
export const FIREBASE_SUB_INVALID = 'FIREBASE_SUB_INVALID'

export const FIREBASE_LOG_FIRED = 'FIREBASE_LOG_FIRED'
export const FIREBASE_LOG_SUCCESS = 'FIREBASE_LOG_SUCCESS'
export const FIREBASE_LOG_ERROR = 'FIREBASE_LOG_ERROR'

export const MISSION_NEW = 'MISSION_NEW'
export const MISSION_FIRED = 'MISSION_FIRED'